"""empty message

Revision ID: 04c7a68c2bef
Revises: 
Create Date: 2018-06-21 20:28:47.466204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04c7a68c2bef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autotest_interface_testcase', sa.Column('testcase_query', mysql.JSON(), nullable=True))
    op.drop_column('autotest_system_setting', 'is_used')
    op.add_column('autotest_testcasegroup', sa.Column('runner_setting_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('autotest_testcasegroup', 'runner_setting_id')
    op.add_column('autotest_system_setting', sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('autotest_interface_testcase', 'testcase_query')
    # ### end Alembic commands ###
