"""empty message

Revision ID: 0602121991d2
Revises: 49a675f1f0ff
Create Date: 2018-05-24 16:47:35.690463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0602121991d2'
down_revision = '49a675f1f0ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('autotest_result', 'testcase_testgroup_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autotest_result', sa.Column('testcase_testgroup_id', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
