"""empty message

Revision ID: 1b8b62ed8dde
Revises: f95323f4ee25
Create Date: 2018-06-19 17:22:03.211206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b8b62ed8dde'
down_revision = 'f95323f4ee25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('autotest_system_setting', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autotest_system_setting', sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
