"""empty message

Revision ID: 38da990c9625
Revises: 1b8b62ed8dde
Create Date: 2018-06-19 17:22:50.737581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '38da990c9625'
down_revision = '1b8b62ed8dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autotest_system_setting', sa.Column('value', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('autotest_system_setting', 'value')
    # ### end Alembic commands ###
