"""empty message

Revision ID: 49a675f1f0ff
Revises: d3da42d52843
Create Date: 2018-05-24 16:45:42.529726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a675f1f0ff'
down_revision = 'd3da42d52843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autotest_result', sa.Column('report_id', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('autotest_result', 'report_id')
    # ### end Alembic commands ###
