"""empty message

Revision ID: 4b699c5bd162
Revises: b4c36e7d492f
Create Date: 2018-06-19 20:20:25.960591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b699c5bd162'
down_revision = 'b4c36e7d492f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autotest_system_setting', sa.Column('value', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('autotest_system_setting', 'value')
    # ### end Alembic commands ###
