"""empty message

Revision ID: 4b8677cd980b
Revises: 53bd73cee176
Create Date: 2018-05-17 14:43:59.456109

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b8677cd980b'
down_revision = '53bd73cee176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autotest_interface_testcase', sa.Column('testcase_verification', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.alter_column('autotest_interface_testcase', 'testcase_body',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('autotest_interface_testcase', 'testcase_header',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('autotest_interface_testcase', 'testcase_response')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autotest_interface_testcase', sa.Column('testcase_response', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.alter_column('autotest_interface_testcase', 'testcase_header',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('autotest_interface_testcase', 'testcase_body',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('autotest_interface_testcase', 'testcase_verification')
    # ### end Alembic commands ###
