"""empty message

Revision ID: 53bd73cee176
Revises: 9b25e7242f0a
Create Date: 2018-05-17 14:37:44.188510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53bd73cee176'
down_revision = '9b25e7242f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autotest_interface_testcase', sa.Column('module_id', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('autotest_interface_testcase', 'module_id')
    # ### end Alembic commands ###
