"""empty message

Revision ID: 5c546dca51f0
Revises: 
Create Date: 2018-04-27 17:43:50.684903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c546dca51f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Interface',
    sa.Column('InterfaceId', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('interface_name', sa.String(length=200), nullable=False),
    sa.Column('interface_url', sa.String(length=200), nullable=False),
    sa.Column('interface_header', sa.String(length=200), nullable=False),
    sa.Column('interface_body', sa.String(length=200), nullable=False),
    sa.Column('interface_method', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('InterfaceId')
    )
    op.create_index(op.f('ix_Interface_interface_name'), 'Interface', ['interface_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Interface_interface_name'), table_name='Interface')
    op.drop_table('Interface')
    # ### end Alembic commands ###
