"""empty message

Revision ID: 5eb06a206bd3
Revises: e614fb927d0f
Create Date: 2018-05-09 13:55:29.155329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5eb06a206bd3'
down_revision = 'e614fb927d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autotest_Interface',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('interface_name', sa.String(length=200), nullable=False),
    sa.Column('interface_url', sa.String(length=255), nullable=False),
    sa.Column('interface_header', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('interface_body', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('interface_method', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('datachange_createtime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('datachange_lasttime', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autotest_Interface_datachange_lasttime'), 'autotest_Interface', ['datachange_lasttime'], unique=False)
    op.create_index(op.f('ix_autotest_Interface_interface_name'), 'autotest_Interface', ['interface_name'], unique=False)
    op.drop_index('ix_Interface_datachange_lasttime', table_name='Interface')
    op.drop_index('ix_Interface_interface_name', table_name='Interface')
    op.drop_table('Interface')
    op.add_column('autotest_testcasegroup', sa.Column('testcase_desc', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('autotest_testcasegroup', 'testcase_desc')
    op.create_table('Interface',
    sa.Column('id', sa.BIGINT(), server_default=sa.text('nextval(\'"Interface_id_seq"\'::regclass)'), nullable=False),
    sa.Column('interface_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('interface_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('interface_header', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('interface_body', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('interface_method', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('datachange_createtime', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('datachange_lasttime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Interface_pkey')
    )
    op.create_index('ix_Interface_interface_name', 'Interface', ['interface_name'], unique=False)
    op.create_index('ix_Interface_datachange_lasttime', 'Interface', ['datachange_lasttime'], unique=False)
    op.drop_index(op.f('ix_autotest_Interface_interface_name'), table_name='autotest_Interface')
    op.drop_index(op.f('ix_autotest_Interface_datachange_lasttime'), table_name='autotest_Interface')
    op.drop_table('autotest_Interface')
    # ### end Alembic commands ###
