"""empty message

Revision ID: 83ae4cbffb18
Revises: 0602121991d2
Create Date: 2018-05-24 16:47:54.668276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ae4cbffb18'
down_revision = '0602121991d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autotest_result', sa.Column('testcase_testgroup_id', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('autotest_result', 'testcase_testgroup_id')
    # ### end Alembic commands ###
