"""empty message

Revision ID: adcff69a32c7
Revises: db34b0765e3f
Create Date: 2018-06-21 14:37:29.116323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'adcff69a32c7'
down_revision = 'db34b0765e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autotest_interface_testcase', sa.Column('testcase_query', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('autotest_interface_testcase', 'testcase_query')
    # ### end Alembic commands ###
