"""empty message

Revision ID: b4c36e7d492f
Revises: dada29f0410d
Create Date: 2018-06-19 20:19:59.683075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4c36e7d492f'
down_revision = 'dada29f0410d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('autotest_system_setting', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autotest_system_setting', sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
