"""empty message

Revision ID: c40471ee67f6
Revises: 83ae4cbffb18
Create Date: 2018-06-05 16:39:42.778386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c40471ee67f6'
down_revision = '83ae4cbffb18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autotest_Interface', sa.Column('interface_desc', sa.Text(), nullable=True))
    op.add_column('autotest_Interface', sa.Column('interface_query', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('autotest_Interface', 'interface_query')
    op.drop_column('autotest_Interface', 'interface_desc')
    # ### end Alembic commands ###
