"""empty message

Revision ID: c5acffd9bf4e
Revises: 
Create Date: 2018-07-13 15:22:34.901482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5acffd9bf4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autotest_timedtask',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('task_type', sa.Integer(), nullable=False),
    sa.Column('testgroup_id', sa.BigInteger(), nullable=False),
    sa.Column('task_desc', sa.String(), nullable=False),
    sa.Column('task_config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('datachange_createtime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('datachange_lasttime', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autotest_timedtask_datachange_lasttime'), 'autotest_timedtask', ['datachange_lasttime'], unique=False)
    op.create_index(op.f('ix_autotest_timedtask_testgroup_id'), 'autotest_timedtask', ['testgroup_id'], unique=False)
    op.drop_index('ix_autotest_scheduledtask_datachange_lasttime', table_name='autotest_scheduledtask')
    op.drop_index('ix_autotest_scheduledtask_module_id', table_name='autotest_scheduledtask')
    op.drop_index('ix_autotest_scheduledtask_testcase_id', table_name='autotest_scheduledtask')
    op.drop_table('autotest_scheduledtask')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autotest_scheduledtask',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('task_type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('module_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('testcase_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('task_desc', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('time_interval', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_execution_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('next_execution_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('task_result', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('datachange_createtime', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('datachange_lasttime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='autotest_scheduledtask_pkey')
    )
    op.create_index('ix_autotest_scheduledtask_testcase_id', 'autotest_scheduledtask', ['testcase_id'], unique=False)
    op.create_index('ix_autotest_scheduledtask_module_id', 'autotest_scheduledtask', ['module_id'], unique=False)
    op.create_index('ix_autotest_scheduledtask_datachange_lasttime', 'autotest_scheduledtask', ['datachange_lasttime'], unique=False)
    op.drop_index(op.f('ix_autotest_timedtask_testgroup_id'), table_name='autotest_timedtask')
    op.drop_index(op.f('ix_autotest_timedtask_datachange_lasttime'), table_name='autotest_timedtask')
    op.drop_table('autotest_timedtask')
    # ### end Alembic commands ###
