"""empty message

Revision ID: dada29f0410d
Revises: 
Create Date: 2018-06-19 20:14:33.003551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dada29f0410d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autotest_system_setting', sa.Column('desc', sa.Text(), nullable=True))
    op.add_column('autotest_system_setting', sa.Column('type', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('autotest_system_setting', 'type')
    op.drop_column('autotest_system_setting', 'desc')
    # ### end Alembic commands ###
