"""empty message

Revision ID: db34b0765e3f
Revises: 
Create Date: 2018-06-20 17:04:31.216224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db34b0765e3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autotest_testcasegroup', sa.Column('runner_setting_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('autotest_testcasegroup', 'runner_setting_id')
    # ### end Alembic commands ###
