"""empty message

Revision ID: e614fb927d0f
Revises: e1432ac78017
Create Date: 2018-04-28 17:18:44.552782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e614fb927d0f'
down_revision = 'e1432ac78017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autotest_user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('login_name', sa.String(length=20), nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('datachange_createtime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('datachange_lasttime', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autotest_user_datachange_lasttime'), 'autotest_user', ['datachange_lasttime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_autotest_user_datachange_lasttime'), table_name='autotest_user')
    op.drop_table('autotest_user')
    # ### end Alembic commands ###
