"""empty message

Revision ID: e682d52b3c3b
Revises: 00bf3bb87e15
Create Date: 2018-05-14 23:21:08.048673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e682d52b3c3b'
down_revision = '00bf3bb87e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancel_vc_order_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('success', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cancel_vc_order_logs_order_id'), 'cancel_vc_order_logs', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cancel_vc_order_logs_order_id'), table_name='cancel_vc_order_logs')
    op.drop_table('cancel_vc_order_logs')
    # ### end Alembic commands ###
