"""empty message
Revision ID: ef3d382f1d81
Revises: 99e2eed98600
Create Date: 2018-05-24 16:00:53.954441
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef3d382f1d81'
down_revision = '99e2eed98600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autotest_result',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('report_id', sa.BOOLEAN(), nullable=False),
    sa.Column('testcase_testgroup_id', sa.BOOLEAN(), nullable=False),
    sa.Column('result', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('datachange_createtime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('datachange_lasttime', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autotest_result_datachange_lasttime'), 'autotest_result', ['datachange_lasttime'], unique=False)
    op.add_column('autotest_report', sa.Column('error', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('autotest_report', sa.Column('fail', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('autotest_report', sa.Column('is_active', sa.BOOLEAN(), nullable=False))
    op.add_column('autotest_report', sa.Column('success', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('autotest_report', sa.Column('testgroup_id', sa.BigInteger(), nullable=False))
    op.add_column('autotest_report', sa.Column('total', sa.BigInteger(), nullable=True))
    op.alter_column('autotest_report', 'result',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('autotest_report', 'result_log',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('autotest_report', 'testcase_id')
    op.drop_column('autotest_report', 'project_id')
    op.drop_column('autotest_report', 'module_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autotest_report', sa.Column('module_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('autotest_report', sa.Column('project_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('autotest_report', sa.Column('testcase_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.alter_column('autotest_report', 'result_log',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('autotest_report', 'result',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('autotest_report', 'total')
    op.drop_column('autotest_report', 'testgroup_id')
    op.drop_column('autotest_report', 'success')
    op.drop_column('autotest_report', 'is_active')
    op.drop_column('autotest_report', 'fail')
    op.drop_column('autotest_report', 'error')
    op.drop_index(op.f('ix_autotest_result_datachange_lasttime'), table_name='autotest_result')
    op.drop_table('autotest_result')
    # ### end Alembic commands ###
