"""empty message

Revision ID: f95323f4ee25
Revises: 6bc12417342a
Create Date: 2018-06-19 16:59:16.198722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95323f4ee25'
down_revision = '6bc12417342a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autotest_system_setting', sa.Column('desc', sa.Text(), nullable=True))
    op.add_column('autotest_system_setting', sa.Column('type', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('autotest_system_setting', 'type')
    op.drop_column('autotest_system_setting', 'desc')
    # ### end Alembic commands ###
